[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Remove the redirect that's causing issues
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# Ensure XML files are served with the correct content type
[[headers]]
  for = "/*.xml"
  [headers.values]
    Content-Type = "application/xml"

# Ensure proper caching for sitemaps
[[headers]]
  for = "/sitemap*.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/news-sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/archive-sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/images-sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=86400"

